spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankingmanagement
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com:
      bankingmanagement: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/bankingmanagement.log
    path: ./logs


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      exclude: db