spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:bankingmanagement
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: bankingmanagement-api

logging:
  level:
    com:
      bankingmanagement: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/bankingmanagement.log
    path: ./logs


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      exclude: db